CREATE SCHEMA spr;

CREATE TABLE spr.client
(
    id              bigint         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           varchar(32)    NULL,
    "name"          varchar(32)    NOT NULL,
    phone           varchar(32)    NOT NULL
);

COMMENT ON TABLE spr.client IS 'Таблица для хранения информации о клиентах';
COMMENT ON COLUMN spr.client.id IS 'Идентификатор';
COMMENT ON COLUMN spr.client.email IS 'Почтовый адрес';
COMMENT ON COLUMN spr.client.name IS 'ФИО';
COMMENT ON COLUMN spr.client.phone IS 'Номер телефона';

CREATE TABLE spr.order
(
    id              varchar(36)     NOT NULL PRIMARY KEY,
    start_time      timestamp       NOT NULL,
    client_id       bigint          NOT NULL,

    CONSTRAINT order_client_fkey FOREIGN KEY (client_id) REFERENCES spr.client(id)
);

COMMENT ON TABLE spr.order IS 'Таблица для хранения информации о записях';
COMMENT ON COLUMN spr.order.id IS 'Идентификатор';
COMMENT ON COLUMN spr.order.start_time IS 'Время начала';
COMMENT ON COLUMN spr.order.client_id IS 'Идентификатор клиента';

CREATE TABLE spr.schedule
(
    id              bigint          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time      time            NOT NULL,
    end_time        time            NOT NULL
);

COMMENT ON TABLE spr.schedule IS 'Таблица для хранения информации графике работы';
COMMENT ON COLUMN spr.schedule.id IS 'Идентификатор';
COMMENT ON COLUMN spr.schedule.start_time IS 'Время начала';
COMMENT ON COLUMN spr.schedule.end_time IS 'Время окончания';

CREATE TABLE spr.holiday
(
    id              bigint          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month           int             NOT NULL,
    day             int             NOT NULL,
    schedule_id     bigint          NOT NULL,

    CONSTRAINT holiday_schedule_fkey FOREIGN KEY (schedule_id) REFERENCES spr.schedule(id)
);

COMMENT ON TABLE spr.holiday IS 'Таблица для хранения информации о праздниках';
COMMENT ON COLUMN spr.holiday.id IS 'Идентификатор';
COMMENT ON COLUMN spr.holiday.month IS 'Месяц';
COMMENT ON COLUMN spr.holiday.day IS 'День';
COMMENT ON COLUMN spr.holiday.schedule_id IS 'Идентификатор графика работы';

CREATE UNIQUE INDEX idx_schedule on spr.schedule (start_time, end_time);
CREATE UNIQUE INDEX idx_client_phone on spr.client (phone);
CREATE UNIQUE INDEX idx_holiday_date on spr.holiday (month, day);